# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Virtomation
tagline:             'Automation in a virtually contained world...'
description:         'Made by <a href="https://twitter.com/jcpowermac" target="_blank">@jcpowermac</a>.'
url:                 http://jcpowermac.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Joseph Callen
  url:               https://twitter.com/jcpowermac
  email:             jcpowermac@gmail.com

# Custom vars
version:             1.0.0
